title: forked-daapd
description: This is a much updated version of the original forked-daapd 0.19, a Linux/FreeBSD DAAP (iTunes) media server with support for AirPlay devices, Apple Remote (and compatibles), MPD, Spotify, mp3 streaming and internet radio.
google_analytics: UA-68930202-1
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
